### ISSUE TITLE
'make check' fails on arm

### ISSUE THREAD

**Issue by mihidux** [gperftools/gperftools#890]
I'm trying to compile on a Raspberry Pi 3 and I'm getting failures in 'make check'.  Ideas?

```
=========================================
   gperftools 2.5.91: ./test-suite.log
=========================================

# TOTAL: 48
# PASS:  42
# SKIP:  0
# XFAIL: 0
# FAIL:  6
# XPASS: 0
# ERROR: 0

.. contents:: :depth: 2

FAIL: sampling_test.sh
======================

Testing heap output...
Using local file /gperftools/.libs/lt-sampling_test.
Using local file /tmp/sampling_test_dir/out.heap.
Adjusting heap profiles for 1-in-524288 sampling rate
Heap version 2
Use of uninitialized value $address in exists at ./src/pprof line 2845.
FAILED.  Output from ./src/pprof --text /gperftools/.libs/lt-sampling_test /tmp/sampling_test_dir/out.heap
----
Using local file /gperftools/.libs/lt-sampling_test.
Using local file /tmp/sampling_test_dir/out.heap.
Adjusting heap profiles for 1-in-524288 sampling rate
Heap version 2
Use of uninitialized value $address in exists at ./src/pprof line 2845.
Total: 55.0 MB
----

FAIL: heap-checker_unittest.sh
==============================

Testing ./heap-checker_unittest with HEAPCHECK= ... OK
Testing ./heap-checker_unittest with HEAPCHECK=local ... FAILED
Output from the failed run:
----
WARNING: Perftools heap leak checker is active -- Performance may suffer
Segmentation fault
----

FAIL: heap-checker-death_unittest.sh
====================================

Testing ./heap-checker_unittest with HEAPCHECK= ... PASS
Testing ./heap-checker_unittest with HEAP_CHECKER_TEST_NO_THREADS=1 ... FAIL
Wrong exit code: expected: '0'; actual: 139
Output did not match '^PASS$'
Output from failed run:
---
WARNING: Perftools heap leak checker is active -- Performance may suffer
---

FAIL: sampling_debug_test.sh
============================

Testing heap output...
Using local file /gperftools/.libs/lt-sampling_test.
Using local file /tmp/sampling_test_dir/out.heap.
Adjusting heap profiles for 1-in-524288 sampling rate
Heap version 2
Use of uninitialized value $address in exists at ./src/pprof line 2845.
FAILED.  Output from ./src/pprof --text /gperftools/.libs/lt-sampling_test /tmp/sampling_test_dir/out.heap
----
Using local file /gperftools/.libs/lt-sampling_test.
Using local file /tmp/sampling_test_dir/out.heap.
Adjusting heap profiles for 1-in-524288 sampling rate
Heap version 2
Use of uninitialized value $address in exists at ./src/pprof line 2845.
Total: 73.7 MB
----

FAIL: heap-checker_debug_unittest.sh
====================================

Testing ./heap-checker_unittest with HEAPCHECK= ... OK
Testing ./heap-checker_unittest with HEAPCHECK=local ... FAILED
Output from the failed run:
----
WARNING: Perftools heap leak checker is active -- Performance may suffer
Segmentation fault
----

FAIL: profile_handler_unittest
==============================

/gperftools/.libs/lt-profile_handler_unittest: symbol lookup error: /gperftools/.libs/lt-profile_handler_unittest: undefined symbol: _Z19ProfileHandlerResetv
```

**Comment by volviq** [comment]
I have a (maybe) similar problem on SLES11. 
See https://gist.github.com/volviq/7f097bcbb349f17cc188ed0d407908e3  for the test-suite.log and
https://gist.github.com/volviq/d0b281dddde5685fb37812a5294a10c8  for the make check invocation.

To get the build to work I needed to use the suggested compiler flags " -D__STDC_LIMIT_MACROS -D__STDC_CONSTANT_MACROS"  as mentioned in https://github.com/gperftools/gperftools/issues/887

The invocations states I should email the report to gperftools@googlegroups.com - as the groups seems to be way less active then the github project, I assumed it makes more sense to post the problem here?

If I choose to run our Software which links the library, our test case which runs valgrinds memcheck64 causes a hang of the test or the application.

**Comment by alk** [comment]
SIZE_MAX is unrelated to this issue.

So, indeed, arm (and arm64) don't have fully functional heap checker. If you configure with --enable-minimal, all tests should pass.

**Comment by volviq** [comment]
@alk oh, right, this bug is intended to be Arm related. Should I create another one for SLES11 x64 systems?

**Comment by alk** [comment]
SIZE_MAX issue you're referring to is fixed now. Try 2.6rc3 that I just tagged.

**Comment by alk** [comment]
As for arm64, I just double checked on my arm64 chromebook with debian sid chroot. And only heap checker unittests fail. Sampling and profiling tests pass. Double check that you're using libunwind.

**Comment by volviq** [comment]
alk:
SIZE_MAX is  fixed, heap problem still exists:
https://gist.github.com/volviq/38b3b38d519acdddad2f1b0546d7597c
-> should I create an issue which is independent of the "ARM" headline?

**Comment by alk** [comment]
Yes, lets have separate ticket for that. When filing issue, please attach config.log.

**Comment by volviq** [comment]
@alk thanks. Created #891

**Comment by mihidux** [comment]
Thanks.  I've verified that configuring with --enable-minimal makes all the tests pass.  Does "--enable-minimal" mean that heap memory checking won't work though?

**Comment by alk** [comment]
Yes, minimal mode disables everything except malloc, so including heap checker.

Heap checker isn't 100% broken on arms, so you may get something out of it. I know that at least part that captures registers of all threads is broken on arms. And yes I plan to fix it (or rather port fix from google-internal code base).

Keep in mind that address sanitizer is likely to be better for heap checking purpose.

**Comment by mihidux** [comment]
Thanks for the help!

**Comment by zhangyiru** [comment]
> 



> Heap checker isn't 100% broken on arms, so you may get something out of it. I know that at least part that captures registers of all threads is broken on arms. And yes I plan to fix it (or rather port fix from google-internal code base).

any progress?
